<?php $product = $this->getProduct(); ?>
<div xmlns:v="http://rdf.data-vocabulary.org/#">
    <div itemscope itemtype="http://data-vocabulary.org/Product">
        <div itemprop="name" content="<?php echo $product->getName();?>"></div>
        <?php if ($description = $this->getDescription()):?>
            <div itemprop="description" content="<?php echo $description;?>"></div>
        <?php endif;?>
        <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
        <div itemprop="image" content="<?php echo $this->getImage(); ?>"></div>
        <?php if ($category = $this->getCategory()): ?>
            <div itemprop="category" content="<?php echo $category?>"></div>
        <?php endif;?>
        <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
            <div itemprop="price" content="<?php echo $product->getFinalPrice(); ?>"></div>
            <div itemprop="currency" content="<?php echo $this->getCurrencyCode(); ?>"></div>
            <div itemprop="condition" content="used"></div>
            <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
            <div itemprop="availability" content="<?php echo $this->getStockStatus(); ?>"></div>
            <?php if ($qty = $this->getQty()): ?>
                <div itemprop="quantity" content="<?php echo $qty; ?>"></div>
            <?php endif;?>
        </div>
        <?php if ($this->getReviewsCount() > 0):?>
            <div itemprop="review" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">
                <div itemprop="rating" content="<?php echo $this->getRatingSummary(); ?>"></div>
                <div itemprop="count" content="<?php echo $this->getReviewsCount(); ?>"></div>
            </div>
        <?php endif;?>
    </div>
</div>