<?php $product = $this->getProduct(); ?>
<?php $_coreHelper = $this->helper('core');?>

<div xmlns:v="http://rdf.data-vocabulary.org/#">
    <div itemscope itemtype="http://data-vocabulary.org/Product">
        <div itemprop="name" content="<?php echo $product->getName();?>"></div>
        <?php if ($description = $this->getDescription()):?>
            <div itemprop="description" content="<?php echo $description;?>"></div>
        <?php endif;?>
        <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
        <div itemprop="image" content="<?php echo $this->getImage(); ?>"></div>
        <?php if ($category = $this->getCategory()): ?>
            <div itemprop="category" content="<?php echo $category?>"></div>
        <?php endif;?>
        <?php if($product->isConfigurable()): ?>
            <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer-aggregate">
                <div itemprop="lowPrice" content="<?php echo $_coreHelper->currency($product->getFinalPrice(), false, false); ?>"></div>
                <div itemprop="highPrice" content="<?php echo $_coreHelper->currency(Mage::helper('gomage_seobooster')->getProductMaxPrice($product), false, false); ?>"></div>
                <div itemprop="currency" content="<?php echo $this->getCurrencyCode(); ?>"></div>
                <div itemprop="condition" content="used"></div>
                <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
                <div itemprop="availability" content="<?php echo $this->getStockStatus(); ?>"></div>
                <?php if ($qty = $this->getQty()): ?>
                    <div itemprop="quantity" content="<?php echo $qty; ?>"></div>
                <?php endif;?>
            </div>
        <?php elseif($product->isGrouped()):?>
            <?php $_prices = Mage::helper('gomage_seobooster')->getGroupedProductPrices($product); ?>
            <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer-aggregate">
                <div itemprop="lowPrice" content="<?php echo $_coreHelper->currency($_prices->getMinPrice(), false, false); ?>"></div>
                <div itemprop="highPrice" content="<?php echo $_coreHelper->currency($_prices->getMaxPrice(), false, false); ?>"></div>
                <div itemprop="currency" content="<?php echo $this->getCurrencyCode(); ?>"></div>
                <div itemprop="condition" content="used"></div>
                <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
                <div itemprop="availability" content="<?php echo $this->getStockStatus(); ?>"></div>
                <?php if ($qty = $this->getQty()): ?>
                    <div itemprop="quantity" content="<?php echo $qty; ?>"></div>
                <?php endif;?>
            </div>
        <?php elseif($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE):?>
            <?php list($_minimalPrice, $_maximalPrice) = $product->getPriceModel()->getTotalPrices($product, null, null, false) ?>
            <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer-aggregate">
                <div itemprop="lowPrice" content="<?php echo $_minimalPrice; ?>"></div>
                <div itemprop="highPrice" content="<?php echo $_maximalPrice; ?>"></div>
                <div itemprop="currency" content="<?php echo $this->getCurrencyCode(); ?>"></div>
                <div itemprop="condition" content="used"></div>
                <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
                <div itemprop="availability" content="<?php echo $this->getStockStatus(); ?>"></div>
                <?php if ($qty = $this->getQty()): ?>
                    <div itemprop="quantity" content="<?php echo $qty; ?>"></div>
                <?php endif;?>
            </div>
        <?php else: ?>
            <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
                <div itemprop="price" content="<?php echo $_coreHelper->currency($product->getFinalPrice(), false, false); ?>"></div>
                <div itemprop="currency" content="<?php echo $this->getCurrencyCode(); ?>"></div>
                <div itemprop="condition" content="used"></div>
                <div itemprop="identifier" content="sku:<?php echo $product->getSku();?>"></div>
                <div itemprop="availability" content="<?php echo $this->getStockStatus(); ?>"></div>
                <?php if ($qty = $this->getQty()): ?>
                    <div itemprop="quantity" content="<?php echo $qty; ?>"></div>
                <?php endif;?>
            </div>
        <?php endif;?>
        <?php if ($this->getReviewsCount() > 0):?>
            <div itemprop="review" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">
                <div itemprop="rating" content="<?php echo $this->getRatingSummary(); ?>"></div>
                <div itemprop="count" content="<?php echo $this->getReviewsCount(); ?>"></div>
            </div>
        <?php endif;?>
    </div>
    <?php if ($this->isBreadcrumbs()): ?>
        <?php if ($categories = $this->getCategories()): ?>
            <?php foreach($categories as $category): ?>
                <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                    <a href="<?php echo $category->getUrl(); ?>" itemprop="url">
                        <span itemprop="title"><?php echo $category->getName(); ?></span>
                    </a>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
            <a href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" itemprop="url">
                <span itemprop="title"><?php echo $product->getName(); ?></span>
            </a>
        </div>
    <?php endif; ?>
</div>