<h3><?php echo $this->getTitle(); ?></h3>
<?php $_items = $this->getCollection(); ?>
<?php if($_items->getSize()): ?>
    <ul class="sitemap">
        <?php foreach ($_items as $_item): ?>
            <li ><a href="<?php echo $this->getItemUrl($_item) ?>"><?php echo $_item->getTitle() ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p class="note-msg">
        <?php echo $this->__('There are no %s available.', $this->getTitle()); ?>
    </p>
<?php endif ?>