<?php
/**
 * GoMage Seo Booster Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2014 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>

<?php	
	$attribute 		= $this->getAttributeModel();
	$attribute_code = $attribute->getAttributeCode();
	$request		= Mage::helper('gomage_navigation')->getRequest();
	
	$_from	= Mage::getSingleton('core/url')->escape($request->getParam($this->_filter->getRequestVar().'_from', ''));
   	$_to	= Mage::getSingleton('core/url')->escape($request->getParam($this->_filter->getRequestVar().'_to', ''));
	
?>
<div class="filter-type-input" style="padding:0;">
	<form onsubmit="GomageNavigation.submitNavigationForm(this, '<?php echo Mage::helper('gomage_seoboosterbridge')->getCurrentUrl(array($this->_filter->getRequestVar().'_from'=>null, $this->_filter->getRequestVar().'_to'=>null), $this->ajaxEnabled()) ?>', <?php echo $this->ajaxEnabled() ?>);return false;" action="'<?php echo Mage::helper('gomage_seoboosterbridge')->getCurrentUrl(array($this->_filter->getRequestVar().'_from'=>null, $this->_filter->getRequestVar().'_to'=>null), $this->ajaxEnabled()) ?>'">
		<fieldset class="filter-fieldset">
		
		<div class="fields">
		<div class="from-wrapper">
			<label><!--<span><?php //echo $this->__('From')?></span>--><input class="input-text navigation-from" type="text" name="<?php echo $attribute_code;?>_from" value="<?php echo $_from;?>" /></label>
		</div>
		
		<div class="from-wrapper">
			<label><span><?php echo $this->__('to')?></span><input class="input-text navigation-to" type="text" name="<?php echo $attribute_code;?>_to" value="<?php echo $_to;?>" /></label>
		</div>
		
		</div>
		
		<div class="slider-input-action">
		
		<button class="button" type="submit"><span><span><?php echo Mage::helper('gomage_navigation')->getFilter();?></span></span></button>
		
		</div>
		</fieldset>
	</form>
</div>